# Generated by Django 5.0.1 on 2024-02-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_useripaddress_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useripaddress',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
