# Generated by Django 5.0.1 on 2024-02-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useripaddress_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useripaddress',
            options={'verbose_name': 'IP Address', 'verbose_name_plural': 'IP Addresses'},
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
