# Generated by Django 5.0.1 on 2024-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_useripaddress_options_useripaddress_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripaddress',
            name='user_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
